In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/DATA E/train.xlsx')
print(df.head())
print(df.shape)

   UNIQUEID  DISBURSED_AMOUNT  ASSET_COST    LTV  BRANCH_ID  SUPPLIER_ID  \
0    420825             50578       58400  89.55         67        22807
1    537409             47145       65550  73.23         67        22807
2    417566             53278       61360  89.63         67        22807
3    624493             57513       66113  88.48         67        22807
4    539055             52378       60300  88.39         67        22807

   MANUFACTURER_ID  CURRENT_PINCODE_ID DATE_OF_BIRTH EMPLOYMENT_TYPE  ...  \
0               45                1441    1984-01-01        Salaried  ...
1               45                1502    1985-07-31   Self employed  ...
2               45                1497    1985-08-24   Self employed  ...
3               45                1501    1993-12-30   Self employed  ...
4               45                1495    1977-12-09   Self employed  ...

  SEC_SANCTIONED_AMOUNT  SEC_DISBURSED_AMOUNT  PRIMARY_INSTAL_AMT  \
0                     0                     0                   0
1                     0                     0                1991
2                     0                     0                   0
3                     0                     0                  31
4                     0                     0                   0

   SEC_INSTAL_AMT  NEW_ACCTS_IN_LAST_SIX_MONTHS  \
0               0                             0
1               0                             0
2               0                             0
3               0                             0
4               0                             0

   DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS  AVERAGE_ACCT_AGE  \
0                                    0         0yrs 0mon
1                                    1        1yrs 11mon
2                                    0         0yrs 0mon
3                                    0         0yrs 8mon
4                                    0         0yrs 0mon

   CREDIT_HISTORY_LENGTH  NO_OF_INQUIRIES  LOAN_DEFAULT
0              0yrs 0mon                0             0
1             1yrs 11mon                0             1
2              0yrs 0mon                0             0
3              1yrs 3mon                1             1
4              0yrs 0mon                1             1

[5 rows x 41 columns]
(233154, 41)

In [ ]:
df.head(5)

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,DATE_OF_BIRTH,EMPLOYMENT_TYPE,...,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT
0,420825,50578,58400,89.55,67,22807,45,1441,1984-01-01,Salaried,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
1,537409,47145,65550,73.23,67,22807,45,1502,1985-07-31,Self employed,...,0,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1
2,417566,53278,61360,89.63,67,22807,45,1497,1985-08-24,Self employed,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
3,624493,57513,66113,88.48,67,22807,45,1501,1993-12-30,Self employed,...,0,0,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1
4,539055,52378,60300,88.39,67,22807,45,1495,1977-12-09,Self employed,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1

In [ ]:
df.columns.tolist()

['UNIQUEID',
 'DISBURSED_AMOUNT',
 'ASSET_COST',
 'LTV',
 'BRANCH_ID',
 'SUPPLIER_ID',
 'MANUFACTURER_ID',
 'CURRENT_PINCODE_ID',
 'DATE_OF_BIRTH',
 'EMPLOYMENT_TYPE',
 'DISBURSAL_DATE',
 'STATE_ID',
 'EMPLOYEE_CODE_ID',
 'MOBILENO_AVL_FLAG',
 'AADHAR_FLAG',
 'PAN_FLAG',
 'VOTERID_FLAG',
 'DRIVING_FLAG',
 'PASSPORT_FLAG',
 'PERFORM_CNS_SCORE',
 'PERFORM_CNS_SCORE_DESCRIPTION',
 'PRI_NO_OF_ACCTS',
 'PRI_ACTIVE_ACCTS',
 'PRI_OVERDUE_ACCTS',
 'PRI_CURRENT_BALANCE',
 'PRI_SANCTIONED_AMOUNT',
 'PRI_DISBURSED_AMOUNT',
 'SEC_NO_OF_ACCTS',
 'SEC_ACTIVE_ACCTS',
 'SEC_OVERDUE_ACCTS',
 'SEC_CURRENT_BALANCE',
 'SEC_SANCTIONED_AMOUNT',
 'SEC_DISBURSED_AMOUNT',
 'PRIMARY_INSTAL_AMT',
 'SEC_INSTAL_AMT',
 'NEW_ACCTS_IN_LAST_SIX_MONTHS',
 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS',
 'AVERAGE_ACCT_AGE',
 'CREDIT_HISTORY_LENGTH',
 'NO_OF_INQUIRIES',
 'LOAN_DEFAULT']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   UNIQUEID                             233154 non-null  int64
 1   DISBURSED_AMOUNT                     233154 non-null  int64
 2   ASSET_COST                           233154 non-null  int64
 3   LTV                                  233154 non-null  float64
 4   BRANCH_ID                            233154 non-null  int64
 5   SUPPLIER_ID                          233154 non-null  int64
 6   MANUFACTURER_ID                      233154 non-null  int64
 7   CURRENT_PINCODE_ID                   233154 non-null  int64
 8   DATE_OF_BIRTH                        233154 non-null  datetime64[ns]
 9   EMPLOYMENT_TYPE                      225493 non-null  object
 10  DISBURSAL_DATE                       233154 non-null  datetime64[ns]
 11  STATE_ID                             233154 non-null  int64
 12  EMPLOYEE_CODE_ID                     233154 non-null  int64
 13  MOBILENO_AVL_FLAG                    233154 non-null  int64
 14  AADHAR_FLAG                          233154 non-null  int64
 15  PAN_FLAG                             233154 non-null  int64
 16  VOTERID_FLAG                         233154 non-null  int64
 17  DRIVING_FLAG                         233154 non-null  int64
 18  PASSPORT_FLAG                        233154 non-null  int64
 19  PERFORM_CNS_SCORE                    233154 non-null  int64
 20  PERFORM_CNS_SCORE_DESCRIPTION        233154 non-null  object
 21  PRI_NO_OF_ACCTS                      233154 non-null  int64
 22  PRI_ACTIVE_ACCTS                     233154 non-null  int64
 23  PRI_OVERDUE_ACCTS                    233154 non-null  int64
 24  PRI_CURRENT_BALANCE                  233154 non-null  int64
 25  PRI_SANCTIONED_AMOUNT                233154 non-null  int64
 26  PRI_DISBURSED_AMOUNT                 233154 non-null  int64
 27  SEC_NO_OF_ACCTS                      233154 non-null  int64
 28  SEC_ACTIVE_ACCTS                     233154 non-null  int64
 29  SEC_OVERDUE_ACCTS                    233154 non-null  int64
 30  SEC_CURRENT_BALANCE                  233154 non-null  int64
 31  SEC_SANCTIONED_AMOUNT                233154 non-null  int64
 32  SEC_DISBURSED_AMOUNT                 233154 non-null  int64
 33  PRIMARY_INSTAL_AMT                   233154 non-null  int64
 34  SEC_INSTAL_AMT                       233154 non-null  int64
 35  NEW_ACCTS_IN_LAST_SIX_MONTHS         233154 non-null  int64
 36  DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS  233154 non-null  int64
 37  AVERAGE_ACCT_AGE                     233154 non-null  object
 38  CREDIT_HISTORY_LENGTH                233154 non-null  object
 39  NO_OF_INQUIRIES                      233154 non-null  int64
 40  LOAN_DEFAULT                         233154 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(34), object(4)
memory usage: 72.9+ MB

In [ ]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

EMPLOYMENT_TYPE    7661
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,DATE_OF_BIRTH,DISBURSAL_DATE,...,SEC_OVERDUE_ACCTS,SEC_CURRENT_BALANCE,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,NO_OF_INQUIRIES,LOAN_DEFAULT
count,233154.000000,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154,233154,...,233154.000000,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000
mean,535917.573376,54356.993528,7.586507e+04,74.746530,72.936094,19638.635035,69.028054,3396.880247,1984-04-04 04:32:39.947502464,2018-09-23 09:57:53.079596032,...,0.007244,5.427793e+03,7.295923e+03,7.179998e+03,1.310548e+04,3.232684e+02,0.381833,0.097481,0.206615,0.217071
min,417428.000000,13320.000000,3.700000e+04,10.030000,1.000000,10524.000000,45.000000,1.000000,1949-09-15 00:00:00,2018-08-01 00:00:00,...,0.000000,-5.746470e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,476786.250000,47145.000000,6.571700e+04,68.880000,14.000000,16535.000000,48.000000,1511.000000,1977-05-04 00:00:00,2018-08-30 00:00:00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
50%,535978.500000,53803.000000,7.094600e+04,76.800000,61.000000,20333.000000,86.000000,2970.000000,1986-01-01 00:00:00,2018-09-25 00:00:00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
75%,595039.750000,60413.000000,7.920175e+04,83.670000,130.000000,23000.000000,86.000000,5677.000000,1992-05-19 00:00:00,2018-10-21 00:00:00,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.999000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000
max,671084.000000,990572.000000,1.628992e+06,95.000000,261.000000,24803.000000,156.000000,7345.000000,2000-10-20 00:00:00,2018-10-31 00:00:00,...,8.000000,3.603285e+07,3.000000e+07,3.000000e+07,2.564281e+07,4.170901e+06,35.000000,20.000000,36.000000,1.000000
std,68315.693711,12971.314171,1.894478e+04,11.456636,69.834995,3491.949566,22.141304,2238.147502,NaN,NaN,...,0.111079,1.702370e+05,1.831560e+05,1.825925e+05,1.513679e+05,1.555369e+04,0.955107,0.384439,0.706498,0.412252

In [ ]:
df['LOAN_DEFAULT'].value_counts()

LOAN_DEFAULT
0    182543
1     50611
Name: count, dtype: int64

In [ ]:
df['LOAN_DEFAULT'].value_counts(normalize=True)*100

LOAN_DEFAULT
0    78.292888
1    21.707112
Name: proportion, dtype: float64

In [ ]:
df.select_dtypes(include='object').columns.tolist()

['EMPLOYMENT_TYPE',
 'PERFORM_CNS_SCORE_DESCRIPTION',
 'AVERAGE_ACCT_AGE',
 'CREDIT_HISTORY_LENGTH']

In [ ]:
df['EMPLOYMENT_TYPE'].value_counts(dropna=False)

EMPLOYMENT_TYPE
Self employed    127635
Salaried          97858
NaN                7661
Name: count, dtype: int64

In [ ]:
df['PERFORM_CNS_SCORE_DESCRIPTION'].value_counts()

PERFORM_CNS_SCORE_DESCRIPTION
No Bureau History Available                                116950
C-Very Low Risk                                             16045
A-Very Low Risk                                             14124
D-Very Low Risk                                             11358
B-Very Low Risk                                              9201
M-Very High Risk                                             8776
F-Low Risk                                                   8485
K-High Risk                                                  8277
H-Medium Risk                                                6855
E-Low Risk                                                   5821
I-Medium Risk                                                5557
G-Low Risk                                                   3988
Not Scored: Sufficient History Not Available                 3765
J-High Risk                                                  3748
Not Scored: Not Enough Info available on the customer        3672
Not Scored: No Activity seen on the customer (Inactive)      2885
Not Scored: No Updates available in last 36 months           1534
L-Very High Risk                                             1134
Not Scored: Only a Guarantor                                  976
Not Scored: More than 50 active Accounts found                  3
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    df['EMPLOYMENT_TYPE'],
    df['LOAN_DEFAULT'],
    margins=True,
    normalize='index'
) * 100

LOAN_DEFAULT             0          1
EMPLOYMENT_TYPE
Salaried         79.654193  20.345807
Self employed    77.234301  22.765699
All              78.284470  21.715530

In [ ]:
default_score = pd.crosstab(
    df['PERFORM_CNS_SCORE_DESCRIPTION'],
    df['LOAN_DEFAULT'],
    normalize='index'
) * 100

default_score.sort_values(1, ascending=False)

LOAN_DEFAULT                                                 0          1
PERFORM_CNS_SCORE_DESCRIPTION
M-Very High Risk                                     69.541933  30.458067
L-Very High Risk                                     71.957672  28.042328
K-High Risk                                          72.187991  27.812009
I-Medium Risk                                        72.737088  27.262912
Not Scored: Sufficient History Not Available         74.422311  25.577689
J-High Risk                                          74.759872  25.240128
H-Medium Risk                                        75.813275  24.186725
No Bureau History Available                          76.868747  23.131253
Not Scored: Only a Guarantor                         78.688525  21.311475
Not Scored: Not Enough Info available on the cu...   79.030501  20.969499
G-Low Risk                                           80.290873  19.709127
Not Scored: No Updates available in last 36 months   80.964798  19.035202
F-Low Risk                                           81.378904  18.621096
Not Scored: No Activity seen on the customer (I...   81.629116  18.370884
C-Very Low Risk                                      82.736055  17.263945
E-Low Risk                                           82.820821  17.179179
A-Very Low Risk                                      83.425375  16.574625
D-Very Low Risk                                      85.041381  14.958619
B-Very Low Risk                                      86.870992  13.129008
Not Scored: More than 50 active Accounts found      100.000000   0.000000

In [ ]:
df['PERFORM_CNS_SCORE'].describe()

count    233154.000000
mean        289.462994
std         338.374779
min           0.000000
25%           0.000000
50%           0.000000
75%         678.000000
max         890.000000
Name: PERFORM_CNS_SCORE, dtype: float64

In [ ]:
df['PERFORM_CNS_SCORE'].value_counts().head(20)

PERFORM_CNS_SCORE
0      116950
300      8776
738      8662
825      7393
15       3765
17       3672
763      3026
16       2885
708      2104
737      1989
836      1927
18       1534
749      1406
710      1245
680      1075
832      1049
726      1042
681      1031
706       985
14        976
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    df['PERFORM_CNS_SCORE'] == 0,
    df['LOAN_DEFAULT'],
    normalize='index'
) * 100

LOAN_DEFAULT               0          1
PERFORM_CNS_SCORE
False              79.726171  20.273829
True               76.868747  23.131253

In [ ]:
df.groupby('LOAN_DEFAULT')['LTV'].describe()

,count,mean,std,min,25%,50%,75%,max
LOAN_DEFAULT,,,,,,,,
0,182543.0,74.154093,11.681455,10.03,68.020,76.00,83.16,95.0
1,50611.0,76.883322,10.327771,15.30,72.055,79.06,84.68,95.0

In [ ]:
df.groupby('LOAN_DEFAULT')['DISBURSED_AMOUNT'].describe()

,count,mean,std,min,25%,50%,75%,max
LOAN_DEFAULT,,,,,,,,
0,182543.0,53826.471111,13140.699007,13320.0,46369.0,53303.0,59947.0,990572.0
1,50611.0,56270.473869,12150.255527,13369.0,49303.0,55459.0,61947.0,191392.0

In [ ]:
df.groupby('LOAN_DEFAULT')['ASSET_COST'].describe()

,count,mean,std,min,25%,50%,75%,max
LOAN_DEFAULT,,,,,,,,
0,182543.0,75722.806128,19015.002867,37000.0,65680.0,70845.0,78999.0,1628992.0
1,50611.0,76378.176661,18680.502609,37000.0,65894.0,71326.0,80061.5,281164.0

In [ ]:
df['AGE'] = (
    pd.Timestamp('2018-10-31') -
    df['DATE_OF_BIRTH']
).dt.days // 365

In [ ]:
df.groupby('LOAN_DEFAULT')['AGE'].describe()

                 count       mean       std   min   25%   50%   75%   max
LOAN_DEFAULT
0             182543.0  34.209167  9.849809  18.0  26.0  32.0  41.0  69.0
1              50611.0  33.332023  9.672310  18.0  25.0  31.0  40.0  64.0

In [ ]:
branch_default = (
    df.groupby('BRANCH_ID')['LOAN_DEFAULT']
      .mean()
      .sort_values(ascending=False)
      * 100
)

branch_default.head(10)

BRANCH_ID
251    34.391259
254    32.430842
97     31.362468
36     29.676178
78     29.147571
153    28.612717
117    28.315412
146    28.255208
105    28.246753
65     28.184668
Name: LOAN_DEFAULT, dtype: float64

In [ ]:
numeric_cols = [
    'DISBURSED_AMOUNT',
    'ASSET_COST',
    'LTV',
    'PERFORM_CNS_SCORE',
    'PRI_CURRENT_BALANCE',
    'PRI_SANCTIONED_AMOUNT',
    'PRI_DISBURSED_AMOUNT',
    'NO_OF_INQUIRIES'
]

corr = df[numeric_cols + ['LOAN_DEFAULT']].corr()

corr['LOAN_DEFAULT'].sort_values(ascending=False)

LOAN_DEFAULT             1.000000
LTV                      0.098208
DISBURSED_AMOUNT         0.077675
NO_OF_INQUIRIES          0.043678
ASSET_COST               0.014261
PRI_DISBURSED_AMOUNT    -0.011155
PRI_SANCTIONED_AMOUNT   -0.011304
PRI_CURRENT_BALANCE     -0.027386
PERFORM_CNS_SCORE       -0.057929
Name: LOAN_DEFAULT, dtype: float64

In [ ]:
pd.qcut(
    df['LTV'],
    q=4,
    duplicates='drop'
)

0           (83.67, 95.0]
1           (68.88, 76.8]
2           (83.67, 95.0]
3           (83.67, 95.0]
4           (83.67, 95.0]
               ...
233149    (10.029, 68.88]
233150      (68.88, 76.8]
233151    (10.029, 68.88]
233152    (10.029, 68.88]
233153    (10.029, 68.88]
Name: LTV, Length: 233154, dtype: category
Categories (4, interval[float64, right]): [(10.029, 68.88] < (68.88, 76.8] < (76.8, 83.67] <
                                           (83.67, 95.0]]

In [ ]:
df['LTV_GROUP'] = pd.qcut(
    df['LTV'],
    q=4,
    duplicates='drop'
)

pd.crosstab(
    df['LTV_GROUP'],
    df['LOAN_DEFAULT'],
    normalize='index'
) * 100

LOAN_DEFAULT             0          1
LTV_GROUP
(10.029, 68.88]  84.402175  15.597825
(68.88, 76.8]    79.090550  20.909450
(76.8, 83.67]    76.340396  23.659604
(83.67, 95.0]    73.334821  26.665179

In [ ]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

DB_USER = "postgres.cpoqdmkxiecxnvvxaoga"
DB_PASSWORD = quote_plus("P180304ilyas")
DB_HOST = "aws-0-ap-southeast-1.pooler.supabase.com"
DB_PORT = "6543"
DB_NAME = "postgres"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

('PostgreSQL 17.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 15.2.0, 64-bit',)

In [ ]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='dw'
"""

pd.read_sql(query, engine)

         table_name
0        dim_branch
1    dim_employment
2  dim_credit_score
3          dim_date
4         fact_loan

In [ ]:
dim_branch = (
    df[['BRANCH_ID']]
    .drop_duplicates()
    .rename(columns={
        'BRANCH_ID':'branch_id'
    })
)

dim_branch.head()

     branch_id
0           67
54          78
134         34
261        130
620         74

In [ ]:
dim_branch.to_sql(
    'dim_branch',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

82

In [ ]:
df['EMPLOYMENT_TYPE'] = (
    df['EMPLOYMENT_TYPE']
    .fillna('Unknown')
)

In [ ]:
dim_employment = (
    df[['EMPLOYMENT_TYPE']]
    .drop_duplicates()
    .rename(columns={
        'EMPLOYMENT_TYPE':'employment_type'
    })
)

dim_employment

   employment_type
0         Salaried
1    Self employed
87         Unknown

In [ ]:
dim_employment.to_sql(
    'dim_employment',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

3

In [ ]:
dim_credit_score = (
    df[['PERFORM_CNS_SCORE_DESCRIPTION']]
    .drop_duplicates()
    .rename(columns={
        'PERFORM_CNS_SCORE_DESCRIPTION':
        'credit_score_desc'
    })
)

dim_credit_score.head()

                                   credit_score_desc
0                        No Bureau History Available
1                                      I-Medium Risk
3                                   L-Very High Risk
5                                    A-Very Low Risk
7  Not Scored: Not Enough Info available on the c...

In [ ]:
dim_credit_score.to_sql(
    'dim_credit_score',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "credit_score_desc" of relation "dim_credit_score" does not exist
LINE 1: INSERT INTO dw.dim_credit_score (credit_score_desc) VALUES (...
                                         ^

[SQL: INSERT INTO dw.dim_credit_score (credit_score_desc) VALUES (%(credit_score_desc__0)s), (%(credit_score_desc__1)s), (%(credit_score_desc__2)s), (%(credit_score_desc__3)s), (%(credit_score_desc__4)s), (%(credit_score_desc__5)s), (%(credit_score_desc__6 ... 277 characters truncated ... e_desc__16)s), (%(credit_score_desc__17)s), (%(credit_score_desc__18)s), (%(credit_score_desc__19)s)]
[parameters: {'credit_score_desc__0': 'No Bureau History Available', 'credit_score_desc__1': 'I-Medium Risk', 'credit_score_desc__2': 'L-Very High Risk', 'credit_score_desc__3': 'A-Very Low Risk', 'credit_score_desc__4': 'Not Scored: Not Enough Info available on the customer', 'credit_score_desc__5': 'D-Very Low Risk', 'credit_score_desc__6': 'M-Very High Risk', 'credit_score_desc__7': 'B-Very Low Risk', 'credit_score_desc__8': 'C-Very Low Risk', 'credit_score_desc__9': 'E-Low Risk', 'credit_score_desc__10': 'H-Medium Risk', 'credit_score_desc__11': 'F-Low Risk', 'credit_score_desc__12': 'K-High Risk', 'credit_score_desc__13': 'Not Scored: No Activity seen on the customer (Inactive)', 'credit_score_desc__14': 'Not Scored: Sufficient History Not Available', 'credit_score_desc__15': 'Not Scored: No Updates available in last 36 months', 'credit_score_desc__16': 'G-Low Risk', 'credit_score_desc__17': 'J-High Risk', 'credit_score_desc__18': 'Not Scored: Only a Guarantor', 'credit_score_desc__19': 'Not Scored: More than 50 active Accounts found'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
dim_date = (
    df[['DISBURSAL_DATE']]
    .drop_duplicates()
    .sort_values('DISBURSAL_DATE')
)

In [ ]:
dim_date['year'] = dim_date['DISBURSAL_DATE'].dt.year
dim_date['month'] = dim_date['DISBURSAL_DATE'].dt.month
dim_date['day'] = dim_date['DISBURSAL_DATE'].dt.day
dim_date['quarter'] = dim_date['DISBURSAL_DATE'].dt.quarter

dim_date = dim_date.rename(
    columns={'DISBURSAL_DATE':'full_date'}
)

In [ ]:
dim_date.to_sql(
    'dim_date',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "date_key" of relation "dim_date" violates not-null constraint
DETAIL:  Failing row contains (null, 2018-08-01, 2018, 8, 1, 3).

[SQL: INSERT INTO dw.dim_date (full_date, year, month, day, quarter) VALUES (%(full_date__0)s, %(year__0)s, %(month__0)s, %(day__0)s, %(quarter__0)s), (%(full_date__1)s, %(year__1)s, %(month__1)s, %(day__1)s, %(quarter__1)s), (%(full_date__2)s, %(year__2)s ... 6388 characters truncated ... )s, %(quarter__82)s), (%(full_date__83)s, %(year__83)s, %(month__83)s, %(day__83)s, %(quarter__83)s)]
[parameters: {'month__0': 8, 'full_date__0': datetime.datetime(2018, 8, 1, 0, 0), 'quarter__0': 3, 'year__0': 2018, 'day__0': 1, 'month__1': 8, 'full_date__1': datetime.datetime(2018, 8, 3, 0, 0), 'quarter__1': 3, 'year__1': 2018, 'day__1': 3, 'month__2': 8, 'full_date__2': datetime.datetime(2018, 8, 4, 0, 0), 'quarter__2': 3, 'year__2': 2018, 'day__2': 4, 'month__3': 8, 'full_date__3': datetime.datetime(2018, 8, 5, 0, 0), 'quarter__3': 3, 'year__3': 2018, 'day__3': 5, 'month__4': 8, 'full_date__4': datetime.datetime(2018, 8, 6, 0, 0), 'quarter__4': 3, 'year__4': 2018, 'day__4': 6, 'month__5': 8, 'full_date__5': datetime.datetime(2018, 8, 7, 0, 0), 'quarter__5': 3, 'year__5': 2018, 'day__5': 7, 'month__6': 8, 'full_date__6': datetime.datetime(2018, 8, 8, 0, 0), 'quarter__6': 3, 'year__6': 2018, 'day__6': 8, 'month__7': 8, 'full_date__7': datetime.datetime(2018, 8, 9, 0, 0), 'quarter__7': 3, 'year__7': 2018, 'day__7': 9, 'month__8': 8, 'full_date__8': datetime.datetime(2018, 8, 10, 0, 0), 'quarter__8': 3, 'year__8': 2018, 'day__8': 10, 'month__9': 8, 'full_date__9': datetime.datetime(2018, 8, 11, 0, 0), 'quarter__9': 3, 'year__9': 2018, 'day__9': 11 ... 320 parameters truncated ... 'month__74': 10, 'full_date__74': datetime.datetime(2018, 10, 22, 0, 0), 'quarter__74': 4, 'year__74': 2018, 'day__74': 22, 'month__75': 10, 'full_date__75': datetime.datetime(2018, 10, 23, 0, 0), 'quarter__75': 4, 'year__75': 2018, 'day__75': 23, 'month__76': 10, 'full_date__76': datetime.datetime(2018, 10, 24, 0, 0), 'quarter__76': 4, 'year__76': 2018, 'day__76': 24, 'month__77': 10, 'full_date__77': datetime.datetime(2018, 10, 25, 0, 0), 'quarter__77': 4, 'year__77': 2018, 'day__77': 25, 'month__78': 10, 'full_date__78': datetime.datetime(2018, 10, 26, 0, 0), 'quarter__78': 4, 'year__78': 2018, 'day__78': 26, 'month__79': 10, 'full_date__79': datetime.datetime(2018, 10, 27, 0, 0), 'quarter__79': 4, 'year__79': 2018, 'day__79': 27, 'month__80': 10, 'full_date__80': datetime.datetime(2018, 10, 28, 0, 0), 'quarter__80': 4, 'year__80': 2018, 'day__80': 28, 'month__81': 10, 'full_date__81': datetime.datetime(2018, 10, 29, 0, 0), 'quarter__81': 4, 'year__81': 2018, 'day__81': 29, 'month__82': 10, 'full_date__82': datetime.datetime(2018, 10, 30, 0, 0), 'quarter__82': 4, 'year__82': 2018, 'day__82': 30, 'month__83': 10, 'full_date__83': datetime.datetime(2018, 10, 31, 0, 0), 'quarter__83': 4, 'year__83': 2018, 'day__83': 31}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
query = """
SELECT column_name
FROM information_schema.columns
WHERE table_schema = 'dw'
AND table_name = 'dim_credit_score'
ORDER BY ordinal_position
"""

pd.read_sql(query, engine)

         column_name
0          score_key
1  score_description

In [ ]:
query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema='dw'
AND table_name='dim_date'
ORDER BY ordinal_position
"""

pd.read_sql(query, engine)

  column_name data_type
0    date_key   integer
1   full_date      date
2        year   integer
3       month   integer
4         day   integer
5     quarter   integer

In [ ]:
dim_credit_score = (
    df[['PERFORM_CNS_SCORE_DESCRIPTION']]
    .drop_duplicates()
    .rename(columns={
        'PERFORM_CNS_SCORE_DESCRIPTION': 'score_description'
    })
)

dim_credit_score.head()

                                   score_description
0                        No Bureau History Available
1                                      I-Medium Risk
3                                   L-Very High Risk
5                                    A-Very Low Risk
7  Not Scored: Not Enough Info available on the c...

In [ ]:
dim_credit_score.columns

Index(['score_description'], dtype='object')

In [ ]:
dim_credit_score.to_sql(
    'dim_credit_score',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

20

In [ ]:
dim_date = (
    df[['DISBURSAL_DATE']]
    .drop_duplicates()
    .sort_values('DISBURSAL_DATE')
)

dim_date['date_key'] = (
    dim_date['DISBURSAL_DATE']
    .dt.strftime('%Y%m%d')
    .astype(int)
)

dim_date['year'] = dim_date['DISBURSAL_DATE'].dt.year
dim_date['month'] = dim_date['DISBURSAL_DATE'].dt.month
dim_date['day'] = dim_date['DISBURSAL_DATE'].dt.day
dim_date['quarter'] = dim_date['DISBURSAL_DATE'].dt.quarter

dim_date = dim_date.rename(
    columns={
        'DISBURSAL_DATE': 'full_date'
    }
)

dim_date = dim_date[
    ['date_key','full_date','year','month','day','quarter']
]

dim_date.head()

      date_key  full_date  year  month  day  quarter
2     20180801 2018-08-01  2018      8    1        3
0     20180803 2018-08-03  2018      8    3        3
286   20180804 2018-08-04  2018      8    4        3
5287  20180805 2018-08-05  2018      8    5        3
39    20180806 2018-08-06  2018      8    6        3

In [ ]:
dim_date.to_sql(
    'dim_date',
    engine,
    schema='dw',
    if_exists='append',
    index=False
)

84

In [ ]:
pd.read_sql(
    "SELECT COUNT(*) FROM dw.dim_branch",
    engine
)

   count
0     82

In [ ]:
dim_branch_db = pd.read_sql(
    "SELECT * FROM dw.dim_branch",
    engine
)

In [ ]:
dim_employment_db = pd.read_sql(
    "SELECT * FROM dw.dim_employment",
    engine
)

In [ ]:
dim_credit_score_db = pd.read_sql(
    "SELECT * FROM dw.dim_credit_score",
    engine
)

In [ ]:
dim_date_db = pd.read_sql(
    "SELECT * FROM dw.dim_date",
    engine
)

In [ ]:
fact_loan = df.copy()

In [ ]:
dim_branch_db.head()

   branch_key  branch_id
0           1         67
1           2         78
2           3         34
3           4        130
4           5         74

In [ ]:
fact_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 43 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   UNIQUEID                             233154 non-null  int64
 1   DISBURSED_AMOUNT                     233154 non-null  int64
 2   ASSET_COST                           233154 non-null  int64
 3   LTV                                  233154 non-null  float64
 4   BRANCH_ID                            233154 non-null  int64
 5   SUPPLIER_ID                          233154 non-null  int64
 6   MANUFACTURER_ID                      233154 non-null  int64
 7   CURRENT_PINCODE_ID                   233154 non-null  int64
 8   DATE_OF_BIRTH                        233154 non-null  datetime64[ns]
 9   EMPLOYMENT_TYPE                      233154 non-null  object
 10  DISBURSAL_DATE                       233154 non-null  datetime64[ns]
 11  STATE_ID                             233154 non-null  int64
 12  EMPLOYEE_CODE_ID                     233154 non-null  int64
 13  MOBILENO_AVL_FLAG                    233154 non-null  int64
 14  AADHAR_FLAG                          233154 non-null  int64
 15  PAN_FLAG                             233154 non-null  int64
 16  VOTERID_FLAG                         233154 non-null  int64
 17  DRIVING_FLAG                         233154 non-null  int64
 18  PASSPORT_FLAG                        233154 non-null  int64
 19  PERFORM_CNS_SCORE                    233154 non-null  int64
 20  PERFORM_CNS_SCORE_DESCRIPTION        233154 non-null  object
 21  PRI_NO_OF_ACCTS                      233154 non-null  int64
 22  PRI_ACTIVE_ACCTS                     233154 non-null  int64
 23  PRI_OVERDUE_ACCTS                    233154 non-null  int64
 24  PRI_CURRENT_BALANCE                  233154 non-null  int64
 25  PRI_SANCTIONED_AMOUNT                233154 non-null  int64
 26  PRI_DISBURSED_AMOUNT                 233154 non-null  int64
 27  SEC_NO_OF_ACCTS                      233154 non-null  int64
 28  SEC_ACTIVE_ACCTS                     233154 non-null  int64
 29  SEC_OVERDUE_ACCTS                    233154 non-null  int64
 30  SEC_CURRENT_BALANCE                  233154 non-null  int64
 31  SEC_SANCTIONED_AMOUNT                233154 non-null  int64
 32  SEC_DISBURSED_AMOUNT                 233154 non-null  int64
 33  PRIMARY_INSTAL_AMT                   233154 non-null  int64
 34  SEC_INSTAL_AMT                       233154 non-null  int64
 35  NEW_ACCTS_IN_LAST_SIX_MONTHS         233154 non-null  int64
 36  DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS  233154 non-null  int64
 37  AVERAGE_ACCT_AGE                     233154 non-null  object
 38  CREDIT_HISTORY_LENGTH                233154 non-null  object
 39  NO_OF_INQUIRIES                      233154 non-null  int64
 40  LOAN_DEFAULT                         233154 non-null  int64
 41  AGE                                  233154 non-null  int64
 42  LTV_GROUP                            233154 non-null  category
dtypes: category(1), datetime64[ns](2), float64(1), int64(35), object(4)
memory usage: 74.9+ MB

In [ ]:
fact_loan.head()

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,DATE_OF_BIRTH,EMPLOYMENT_TYPE,...,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT,AGE,LTV_GROUP
0,420825,50578,58400,89.55,67,22807,45,1441,1984-01-01,Salaried,...,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,34,"(83.67, 95.0]"
1,537409,47145,65550,73.23,67,22807,45,1502,1985-07-31,Self employed,...,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1,33,"(68.88, 76.8]"
2,417566,53278,61360,89.63,67,22807,45,1497,1985-08-24,Self employed,...,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,33,"(83.67, 95.0]"
3,624493,57513,66113,88.48,67,22807,45,1501,1993-12-30,Self employed,...,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1,24,"(83.67, 95.0]"
4,539055,52378,60300,88.39,67,22807,45,1495,1977-12-09,Self employed,...,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1,40,"(83.67, 95.0]"

In [ ]:
dim_branch_db = pd.read_sql(
    "SELECT * FROM dw.dim_branch",
    engine
)

dim_employment_db = pd.read_sql(
    "SELECT * FROM dw.dim_employment",
    engine
)

dim_credit_score_db = pd.read_sql(
    "SELECT * FROM dw.dim_credit_score",
    engine
)

dim_date_db = pd.read_sql(
    "SELECT * FROM dw.dim_date",
    engine
)

In [ ]:
print(dim_branch_db.columns.tolist())
print(dim_employment_db.columns.tolist())
print(dim_credit_score_db.columns.tolist())
print(dim_date_db.columns.tolist())

['branch_key', 'branch_id']
['employment_key', 'employment_type']
['score_key', 'score_description']
['date_key', 'full_date', 'year', 'month', 'day', 'quarter']

In [ ]:
fact = df.copy()

fact = fact.merge(
    dim_branch_db,
    on='BRANCH_ID',
    how='left'
)

KeyError: 'BRANCH_ID'

In [ ]:
fact = fact.merge(
    dim_employment_db,
    left_on='EMPLOYMENT_TYPE',
    right_on='employment_type',
    how='left'
)

In [ ]:
fact = fact.merge(
    dim_credit_score_db,
    left_on='PERFORM_CNS_SCORE_DESCRIPTION',
    right_on='score_description',
    how='left'
)

In [ ]:
fact['DISBURSAL_DATE'] = pd.to_datetime(
    fact['DISBURSAL_DATE']
).dt.date

dim_date_db['full_date'] = pd.to_datetime(
    dim_date_db['full_date']
).dt.date

In [ ]:
fact[
[
    'branch_key',
    'employment_key',
    'score_key',
    'date_key'
]
].isnull().sum()

KeyError: "['branch_key', 'date_key'] not in index"

In [ ]:
fact = df.copy()

In [ ]:
print('BRANCH_ID' in fact.columns)
print('EMPLOYMENT_TYPE' in fact.columns)
print('PERFORM_CNS_SCORE_DESCRIPTION' in fact.columns)
print('DISBURSAL_DATE' in fact.columns)

True
True
True
True

In [ ]:
fact.columns.tolist()

['UNIQUEID',
 'DISBURSED_AMOUNT',
 'ASSET_COST',
 'LTV',
 'BRANCH_ID',
 'SUPPLIER_ID',
 'MANUFACTURER_ID',
 'CURRENT_PINCODE_ID',
 'DATE_OF_BIRTH',
 'EMPLOYMENT_TYPE',
 'DISBURSAL_DATE',
 'STATE_ID',
 'EMPLOYEE_CODE_ID',
 'MOBILENO_AVL_FLAG',
 'AADHAR_FLAG',
 'PAN_FLAG',
 'VOTERID_FLAG',
 'DRIVING_FLAG',
 'PASSPORT_FLAG',
 'PERFORM_CNS_SCORE',
 'PERFORM_CNS_SCORE_DESCRIPTION',
 'PRI_NO_OF_ACCTS',
 'PRI_ACTIVE_ACCTS',
 'PRI_OVERDUE_ACCTS',
 'PRI_CURRENT_BALANCE',
 'PRI_SANCTIONED_AMOUNT',
 'PRI_DISBURSED_AMOUNT',
 'SEC_NO_OF_ACCTS',
 'SEC_ACTIVE_ACCTS',
 'SEC_OVERDUE_ACCTS',
 'SEC_CURRENT_BALANCE',
 'SEC_SANCTIONED_AMOUNT',
 'SEC_DISBURSED_AMOUNT',
 'PRIMARY_INSTAL_AMT',
 'SEC_INSTAL_AMT',
 'NEW_ACCTS_IN_LAST_SIX_MONTHS',
 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS',
 'AVERAGE_ACCT_AGE',
 'CREDIT_HISTORY_LENGTH',
 'NO_OF_INQUIRIES',
 'LOAN_DEFAULT',
 'AGE',
 'LTV_GROUP']

In [ ]:
fact = fact.merge(
    dim_employment_db,
    left_on='EMPLOYMENT_TYPE',
    right_on='employment_type',
    how='left'
)

In [ ]:
fact[['EMPLOYMENT_TYPE','employment_key']].head()

  EMPLOYMENT_TYPE  employment_key
0        Salaried               1
1   Self employed               2
2   Self employed               2
3   Self employed               2
4   Self employed               2

In [ ]:
fact = fact.merge(
    dim_credit_score_db,
    left_on='PERFORM_CNS_SCORE_DESCRIPTION',
    right_on='score_description',
    how='left'
)

In [ ]:
fact[['PERFORM_CNS_SCORE_DESCRIPTION','score_key']].head()

  PERFORM_CNS_SCORE_DESCRIPTION  score_key
0   No Bureau History Available          1
1                 I-Medium Risk          2
2   No Bureau History Available          1
3              L-Very High Risk          3
4   No Bureau History Available          1

In [ ]:
fact['DISBURSAL_DATE'] = pd.to_datetime(
    fact['DISBURSAL_DATE']
).dt.date

dim_date_db['full_date'] = pd.to_datetime(
    dim_date_db['full_date']
).dt.date

In [ ]:
fact = fact.merge(
    dim_date_db[['date_key','full_date']],
    left_on='DISBURSAL_DATE',
    right_on='full_date',
    how='left'
)

In [ ]:
fact[['DISBURSAL_DATE','date_key']].head()

  DISBURSAL_DATE  date_key
0     2018-08-03  20180803
1     2018-09-26  20180926
2     2018-08-01  20180801
3     2018-10-26  20181026
4     2018-09-26  20180926

In [ ]:
fact[
[
    'branch_key',
    'employment_key',
    'score_key',
    'date_key'
]
].isnull().sum()

branch_key        0
employment_key    0
score_key         0
date_key          0
dtype: int64

In [ ]:
fact.columns.tolist()

['UNIQUEID',
 'DISBURSED_AMOUNT',
 'ASSET_COST',
 'LTV',
 'BRANCH_ID',
 'SUPPLIER_ID',
 'MANUFACTURER_ID',
 'CURRENT_PINCODE_ID',
 'DATE_OF_BIRTH',
 'EMPLOYMENT_TYPE',
 'DISBURSAL_DATE',
 'STATE_ID',
 'EMPLOYEE_CODE_ID',
 'MOBILENO_AVL_FLAG',
 'AADHAR_FLAG',
 'PAN_FLAG',
 'VOTERID_FLAG',
 'DRIVING_FLAG',
 'PASSPORT_FLAG',
 'PERFORM_CNS_SCORE',
 'PERFORM_CNS_SCORE_DESCRIPTION',
 'PRI_NO_OF_ACCTS',
 'PRI_ACTIVE_ACCTS',
 'PRI_OVERDUE_ACCTS',
 'PRI_CURRENT_BALANCE',
 'PRI_SANCTIONED_AMOUNT',
 'PRI_DISBURSED_AMOUNT',
 'SEC_NO_OF_ACCTS',
 'SEC_ACTIVE_ACCTS',
 'SEC_OVERDUE_ACCTS',
 'SEC_CURRENT_BALANCE',
 'SEC_SANCTIONED_AMOUNT',
 'SEC_DISBURSED_AMOUNT',
 'PRIMARY_INSTAL_AMT',
 'SEC_INSTAL_AMT',
 'NEW_ACCTS_IN_LAST_SIX_MONTHS',
 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS',
 'AVERAGE_ACCT_AGE',
 'CREDIT_HISTORY_LENGTH',
 'NO_OF_INQUIRIES',
 'LOAN_DEFAULT',
 'AGE',
 'LTV_GROUP',
 'branch_key',
 'branch_id',
 'employment_key',
 'employment_type',
 'score_key',
 'score_description',
 'date_key',
 'full_date']

In [ ]:
fact[
[
    'branch_key',
    'employment_key',
    'score_key',
    'date_key'
]
].isnull().sum()

branch_key        0
employment_key    0
score_key         0
date_key          0
dtype: int64

In [ ]:
fact_final = fact[
    [
        'UNIQUEID',
        'date_key',
        'branch_key',
        'employment_key',
        'score_key',
        'DISBURSED_AMOUNT',
        'ASSET_COST',
        'LTV',
        'PERFORM_CNS_SCORE',
        'PRI_CURRENT_BALANCE',
        'PRI_SANCTIONED_AMOUNT',
        'PRI_DISBURSED_AMOUNT',
        'NO_OF_INQUIRIES',
        'LOAN_DEFAULT'
    ]
].copy()

In [ ]:
fact_final = fact_final.rename(columns={
    'UNIQUEID':'uniqueid',
    'DISBURSED_AMOUNT':'disbursed_amount',
    'ASSET_COST':'asset_cost',
    'LTV':'ltv',
    'PERFORM_CNS_SCORE':'perform_cns_score',
    'PRI_CURRENT_BALANCE':'pri_current_balance',
    'PRI_SANCTIONED_AMOUNT':'pri_sanctioned_amount',
    'PRI_DISBURSED_AMOUNT':'pri_disbursed_amount',
    'NO_OF_INQUIRIES':'no_of_inquiries',
    'LOAN_DEFAULT':'loan_default'
})

In [ ]:
fact_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   uniqueid               233154 non-null  int64
 1   date_key               233154 non-null  int64
 2   branch_key             233154 non-null  int64
 3   employment_key         233154 non-null  int64
 4   score_key              233154 non-null  int64
 5   disbursed_amount       233154 non-null  int64
 6   asset_cost             233154 non-null  int64
 7   ltv                    233154 non-null  float64
 8   perform_cns_score      233154 non-null  int64
 9   pri_current_balance    233154 non-null  int64
 10  pri_sanctioned_amount  233154 non-null  int64
 11  pri_disbursed_amount   233154 non-null  int64
 12  no_of_inquiries        233154 non-null  int64
 13  loan_default           233154 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 24.9 MB

In [ ]:
fact_final.isnull().sum()

uniqueid                 0
date_key                 0
branch_key               0
employment_key           0
score_key                0
disbursed_amount         0
asset_cost               0
ltv                      0
perform_cns_score        0
pri_current_balance      0
pri_sanctioned_amount    0
pri_disbursed_amount     0
no_of_inquiries          0
loan_default             0
dtype: int64

In [ ]:
fact_final.to_sql(
    'fact_loan',
    engine,
    schema='dw',
    if_exists='append',
    index=False,
    chunksize=5000,
    method='multi'
)

233154